version: '2'
services:
  ace_data:
    image: chooban/ace-data-container:latest
  api:
    image: chooban/ace-previews-api:latest
    depends_on:
      - ace_data
    volumes_from:
      - ace_data:ro
    ports:
      - 8100
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=debug
  site:
    build: .
  web: 
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - site
      - api
    volumes_from:
      - site
    ports:
      - 80:80

