<?php

$jsonData = json_decode( base64_decode( $_REQUEST['encodeddata'], true ) );

$contents = "Previews Code,Quantity,Title,Price,Publisher,Comment\n";
foreach ( $jsonData->{'line_items'} as $row ) {
  $tmp = sprintf( "%s,%d,%s,%s,%s,%s\n", 
    $row->{'previews'}, 
    $row->{'quantity'},
    $row->{'title'}, 
    $row->{'price'}, 
    $row->{'publisher'}, 
    $row->{'comment'} 
  );
  $contents .= $tmp;
}

$contents .= ",,Total," . ($jsonData->{order_total} / 100) . ",\n";
$contents .= "\nGenerated by Ace My Order";

header("Content-type: text/csv");
header("Content-Disposition: filename=order" . $jsonData->{'issue'} . ".csv");
header("Pragma: no-cache");
header("Expires: 0");

# file_put_contents('php://stderr', print_r($contents, TRUE));
print $contents;

?>
